/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Brayan C
 */
public class DialogEdicionTratamiento extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogEdicionTratamiento.class.getName());

    /**
     * Creates new form DialogEdicionTratamiento
     */
    public DialogEdicionTratamiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brackground = new javax.swing.JPanel();
        lblTituloPanel = new javax.swing.JLabel();
        cmbTratamiento = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        lblTratamiento = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        lblMedicamento = new javax.swing.JLabel();
        txtDosis = new javax.swing.JTextField();
        lblDosis = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObservaciones = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        lblValorId = new javax.swing.JLabel();
        lblValorFecha = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        brackground.setBackground(new java.awt.Color(245, 245, 245));

        lblTituloPanel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTituloPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPanel.setText("Editar registro");

        cmbTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTratamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbTratamiento.setMaximumSize(new java.awt.Dimension(138, 50));
        cmbTratamiento.setMinimumSize(new java.awt.Dimension(137, 49));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTratamiento.setForeground(new java.awt.Color(0, 0, 0));
        lblTratamiento.setText("Tratamiento:");

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        lblId.setText("Id:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha del tratamiento:");

        txtMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lblMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMedicamento.setForeground(new java.awt.Color(0, 0, 0));
        lblMedicamento.setText("Medicamento:");

        txtDosis.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lblDosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDosis.setForeground(new java.awt.Color(0, 0, 0));
        lblDosis.setText("Dosis:");

        lblObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblObservaciones.setForeground(new java.awt.Color(0, 0, 0));
        lblObservaciones.setText("Observaciones:");

        txtAreaObservaciones.setColumns(20);
        txtAreaObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAreaObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtAreaObservaciones);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblValorId.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblValorId.setForeground(new java.awt.Color(0, 0, 0));
        lblValorId.setText("001");

        lblValorFecha.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblValorFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblValorFecha.setText("4/3/23");

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout brackgroundLayout = new javax.swing.GroupLayout(brackground);
        brackground.setLayout(brackgroundLayout);
        brackgroundLayout.setHorizontalGroup(
            brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brackgroundLayout.createSequentialGroup()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(brackgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(brackgroundLayout.createSequentialGroup()
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblValorId, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(brackgroundLayout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblValorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(brackgroundLayout.createSequentialGroup()
                        .addComponent(lblTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cmbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(brackgroundLayout.createSequentialGroup()
                        .addComponent(lblMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(brackgroundLayout.createSequentialGroup()
                        .addComponent(lblDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(brackgroundLayout.createSequentialGroup()
                        .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))))
        );
        brackgroundLayout.setVerticalGroup(
            brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brackgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(brackgroundLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValorId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(brackgroundLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(brackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(brackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(brackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogEdicionTratamiento dialog = new DialogEdicionTratamiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JComboBox<String> getJcbTratamiento() {
        return cmbTratamiento;
    }

    public String getDosis() {
        String dosis = txtDosis.getText();
        
        if (verificarCamposDeTexto(dosis)) {
            return dosis;
        }
        return null;
    }

    public String getMedicamento() {
        String medicamento =  txtMedicamento.getText();
        
        if (verificarCamposDeTexto(medicamento)) {
            return medicamento;
        }
        return null;
    }

    public String getObservaciones() {
        String observaciones = txtAreaObservaciones.getText();
        
        if (verificarCamposDeTexto(observaciones)) {
            return observaciones;
        }
        return null;
    }

    public void setLblFechaTratamiento(String fechaTratamiento) {
        this.lblValorFecha.setText(fechaTratamiento);
    }
    
    public void setLblId(String id) {
        this.lblValorId.setText(id);
    }

    public void setTxtDosis(String dosis) {
        this.txtDosis.setText(dosis);
    }

    public void setTxtMedicamento(String medicamento) {
        this.txtMedicamento.setText(medicamento);
    }

    public void setTxtObservaciones(String observaciones) {
        this.txtAreaObservaciones.setText(observaciones);
    }
    
    private boolean verificarCamposDeTexto(String campoDeTexto) {
        return campoDeTexto != null && !campoDeTexto.trim().isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel brackground;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbTratamiento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDosis;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblTituloPanel;
    private javax.swing.JLabel lblTratamiento;
    private javax.swing.JLabel lblValorFecha;
    private javax.swing.JLabel lblValorId;
    private javax.swing.JTextArea txtAreaObservaciones;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtMedicamento;
    // End of variables declaration//GEN-END:variables
}
