/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;


/**
 *
 * @author Brayan C
 */
public class DialogInformacionUsuario extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogInformacionUsuario.class.getName());

    /**
     * Creates new form DialogInformacionUsuario
     */
    public DialogInformacionUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblNombresApellidos = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblFinca = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        lblVereda = new javax.swing.JLabel();
        lblValorNombresApellidos = new javax.swing.JLabel();
        lblValorUsuario = new javax.swing.JLabel();
        lblValorFinca = new javax.swing.JLabel();
        lblValorDepartamento = new javax.swing.JLabel();
        lblValorCorreo = new javax.swing.JLabel();
        lblValorVereda = new javax.swing.JLabel();
        lblValorMunicipio = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblValorCabezasDeGanado = new javax.swing.JLabel();
        lblCabezasGanado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Información de usuario");
        lblTitulo1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));

        lblNombresApellidos.setBackground(new java.awt.Color(102, 102, 102));
        lblNombresApellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombresApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lblNombresApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombresApellidos.setText("Nombres y apellidos:");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuario.setText("Nombre de usuario:");

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCorreo.setText("Correo electrónico:");

        lblFinca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFinca.setForeground(new java.awt.Color(0, 0, 0));
        lblFinca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFinca.setText("Nombre de la finca:");

        lblDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDepartamento.setText("Departamento:");

        lblMunicipio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMunicipio.setForeground(new java.awt.Color(0, 0, 0));
        lblMunicipio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMunicipio.setText("Municipio:");

        lblVereda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVereda.setForeground(new java.awt.Color(0, 0, 0));
        lblVereda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVereda.setText("Vereda:");

        lblValorNombresApellidos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblValorNombresApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lblValorNombresApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorNombresApellidos.setText("Brayan Stiven Castellanos Diaz");

        lblValorUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblValorUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblValorUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorUsuario.setText("Brayan C");

        lblValorFinca.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblValorFinca.setForeground(new java.awt.Color(0, 0, 0));
        lblValorFinca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorFinca.setText("Finca la hoyada");

        lblValorDepartamento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblValorDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblValorDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorDepartamento.setText("Santander");

        lblValorCorreo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblValorCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblValorCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorCorreo.setText("castellanosbrayan136@gmail.com");

        lblValorVereda.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblValorVereda.setForeground(new java.awt.Color(0, 0, 0));
        lblValorVereda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorVereda.setText("Buenavista");

        lblValorMunicipio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblValorMunicipio.setForeground(new java.awt.Color(0, 0, 0));
        lblValorMunicipio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorMunicipio.setText("Malaga");

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("Información de la finca");
        lblTitulo2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));

        lblValorCabezasDeGanado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        lblValorCabezasDeGanado.setForeground(new java.awt.Color(0, 0, 0));
        lblValorCabezasDeGanado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorCabezasDeGanado.setText("50");

        lblCabezasGanado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCabezasGanado.setForeground(new java.awt.Color(0, 0, 0));
        lblCabezasGanado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCabezasGanado.setText("Cabezas de ganado:");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblNombresApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblValorNombresApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblValorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblValorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblValorFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblValorDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblValorMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addComponent(lblVereda, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(lblValorVereda, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblCabezasGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblValorCabezasDeGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitulo1)
                .addGap(30, 30, 30)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblNombresApellidos))
                    .addComponent(lblValorNombresApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblUsuario))
                    .addComponent(lblValorUsuario))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblCorreo))
                    .addComponent(lblValorCorreo))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblCabezasGanado))
                    .addComponent(lblValorCabezasDeGanado))
                .addGap(18, 18, 18)
                .addComponent(lblTitulo2)
                .addGap(30, 30, 30)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblFinca))
                    .addComponent(lblValorFinca))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValorDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVereda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorVereda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogInformacionUsuario dialog = new DialogInformacionUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setLblCorreo(String correo) {
        this.lblValorCorreo.setText(correo);
    }

    public void setLblDepartamento(String departamento) {
        this.lblValorDepartamento.setText(departamento);
    }

    public void setLblFinca(String finca) {
        this.lblValorFinca.setText(finca);
    }

    public void setLblMunicipio(String municipio) {
        this.lblValorMunicipio.setText(municipio);
    }

    public void setLblNombresApellidos(String nombresApellidos) {
        this.lblValorNombresApellidos.setText(nombresApellidos);
    }

    public void setLblUsuario(String usuario) {
        this.lblValorUsuario.setText(usuario);
    }

    public void setLblVereda(String vereda) {
        this.lblValorVereda.setText(vereda);
    }

    public void setLblCabezasDeGanado(String cabezasDeGanado) {
        this.lblValorCabezasDeGanado.setText(cabezasDeGanado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel lblCabezasGanado;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblFinca;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNombresApellidos;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblValorCabezasDeGanado;
    private javax.swing.JLabel lblValorCorreo;
    private javax.swing.JLabel lblValorDepartamento;
    private javax.swing.JLabel lblValorFinca;
    private javax.swing.JLabel lblValorMunicipio;
    private javax.swing.JLabel lblValorNombresApellidos;
    private javax.swing.JLabel lblValorUsuario;
    private javax.swing.JLabel lblValorVereda;
    private javax.swing.JLabel lblVereda;
    // End of variables declaration//GEN-END:variables
}
