/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author Brayan C
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        pnlEstadisticas = new javax.swing.JPanel();
        lblEstadistica1 = new javax.swing.JLabel();
        lblRegistroTotalHoy = new javax.swing.JLabel();
        lblEstadistica2 = new javax.swing.JLabel();
        lblPromedioVacaHoy = new javax.swing.JLabel();
        lblPromedio15Dias = new javax.swing.JLabel();
        lblEstadistica3 = new javax.swing.JLabel();
        lblEstadistica4 = new javax.swing.JLabel();
        lblVacaMenorProduccion = new javax.swing.JLabel();
        pnlAlertas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAlertas = new javax.swing.JList<>();
        lblTituloAlertas = new javax.swing.JLabel();
        pnlGrafico = new javax.swing.JPanel();

        lblEstadistica1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEstadistica1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadistica1.setText("Registro total de hoy");

        lblRegistroTotalHoy.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblRegistroTotalHoy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistroTotalHoy.setText("56 L");

        lblEstadistica2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEstadistica2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadistica2.setText("Promedio por vaca hoy");

        lblPromedioVacaHoy.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblPromedioVacaHoy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromedioVacaHoy.setText("4.5 L / Vaca");

        lblPromedio15Dias.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblPromedio15Dias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromedio15Dias.setText("53.6 L");

        lblEstadistica3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEstadistica3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadistica3.setText("<html><center>Producción promedio<br>últimos 15 días</center></html>");

        lblEstadistica4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEstadistica4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadistica4.setText("<html><center>Vaca con menor<br>produccion hoy</center></html>");

        lblVacaMenorProduccion.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblVacaMenorProduccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVacaMenorProduccion.setText("991 - Lola");

        javax.swing.GroupLayout pnlEstadisticasLayout = new javax.swing.GroupLayout(pnlEstadisticas);
        pnlEstadisticas.setLayout(pnlEstadisticasLayout);
        pnlEstadisticasLayout.setHorizontalGroup(
            pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadistica1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(lblRegistroTotalHoy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadistica2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(lblPromedioVacaHoy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPromedio15Dias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstadistica3, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVacaMenorProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstadistica4, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlEstadisticasLayout.setVerticalGroup(
            pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEstadistica2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstadisticasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstadistica3)
                            .addComponent(lblEstadistica4)))
                    .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstadistica1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPromedio15Dias, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(lblPromedioVacaHoy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegistroTotalHoy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVacaMenorProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        lstAlertas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lstAlertas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "- Tienes 6 vacas enfermas", "- No has completado el registro de produccion para todas las vaca hoy", "- La vaca lola bajo promedio de produccion de 6 a 2 litros en los ultimos 8 dias", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstAlertas);

        lblTituloAlertas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloAlertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-error-30.png"))); // NOI18N
        lblTituloAlertas.setText("Alertas");
        lblTituloAlertas.setIconTextGap(20);

        javax.swing.GroupLayout pnlAlertasLayout = new javax.swing.GroupLayout(pnlAlertas);
        pnlAlertas.setLayout(pnlAlertasLayout);
        pnlAlertasLayout.setHorizontalGroup(
            pnlAlertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlertasLayout.createSequentialGroup()
                .addGroup(pnlAlertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlAlertasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloAlertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAlertasLayout.setVerticalGroup(
            pnlAlertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlertasLayout.createSequentialGroup()
                .addComponent(lblTituloAlertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAlertas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(pnlEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlAlertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelGrafico() {
        return pnlGrafico;
    }
    
    public JList<String> getListAlertas() {
        return lstAlertas;
    }
    
    public void setJblPromedio15Dias(String promedio15Dias) {
        this.lblPromedio15Dias.setText(promedio15Dias);
    }

    public void setJblRegistroTotalHoy(String registroTotalHoy) {
        this.lblRegistroTotalHoy.setText(registroTotalHoy);
    }

    public void setJblVacaMenorProduccion(String vacaMenorProduccion) {
        this.lblVacaMenorProduccion.setText(vacaMenorProduccion);
    }

    public void setJblPromedioVacaHoy(String promedioVacaHoy) {
        this.lblPromedioVacaHoy.setText(promedioVacaHoy);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstadistica1;
    private javax.swing.JLabel lblEstadistica2;
    private javax.swing.JLabel lblEstadistica3;
    private javax.swing.JLabel lblEstadistica4;
    private javax.swing.JLabel lblPromedio15Dias;
    private javax.swing.JLabel lblPromedioVacaHoy;
    private javax.swing.JLabel lblRegistroTotalHoy;
    private javax.swing.JLabel lblTituloAlertas;
    private javax.swing.JLabel lblVacaMenorProduccion;
    private javax.swing.JList<String> lstAlertas;
    private javax.swing.JPanel pnlAlertas;
    private javax.swing.JPanel pnlEstadisticas;
    private javax.swing.JPanel pnlGrafico;
    // End of variables declaration//GEN-END:variables
}
