/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.time.LocalDate;
import javax.swing.JButton;
import javax.swing.JComboBox;
import modelo.Vaca;

/**
 *
 * @author Brayan C
 */
public class PanelRegistrarProduccion extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrarProduccion
     */
    public PanelRegistrarProduccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblJornada = new javax.swing.JLabel();
        lblMensajeFecha = new javax.swing.JLabel();
        lblMensajeJornada = new javax.swing.JLabel();
        lblMensajeLitros = new javax.swing.JLabel();
        cmbVacas = new javax.swing.JComboBox<>();
        cmbMes = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        cmbAño = new javax.swing.JComboBox<>();
        cmbJornada = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        lblVaca = new javax.swing.JLabel();
        lblLitrosProducidos = new javax.swing.JLabel();
        lblMensajeVaca = new javax.swing.JLabel();
        spnLitros = new javax.swing.JSpinner();
        lblImagen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        background.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Registro producción");

        lblFecha.setBackground(new java.awt.Color(0, 0, 0));
        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha");

        lblJornada.setBackground(new java.awt.Color(0, 0, 0));
        lblJornada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJornada.setForeground(new java.awt.Color(0, 0, 0));
        lblJornada.setText("Jornada");

        lblMensajeFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensajeFecha.setForeground(new java.awt.Color(204, 0, 51));

        lblMensajeJornada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensajeJornada.setForeground(new java.awt.Color(204, 0, 51));

        lblMensajeLitros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensajeLitros.setForeground(new java.awt.Color(204, 0, 51));

        cmbVacas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbVacas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes" }));
        cmbMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día" }));
        cmbDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbAño.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        cmbAño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbJornada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jornada", "Mañana", "Tarde" }));
        cmbJornada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbJornada.setMaximumSize(new java.awt.Dimension(138, 50));
        cmbJornada.setMinimumSize(new java.awt.Dimension(137, 49));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblVaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVaca.setForeground(new java.awt.Color(0, 0, 0));
        lblVaca.setText("Vaca:");

        lblLitrosProducidos.setBackground(new java.awt.Color(0, 0, 0));
        lblLitrosProducidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLitrosProducidos.setForeground(new java.awt.Color(0, 0, 0));
        lblLitrosProducidos.setText("Litros producidos");

        lblMensajeVaca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensajeVaca.setForeground(new java.awt.Color(204, 0, 51));

        spnLitros.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMensajeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLitrosProducidos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblVaca, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spnLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVacas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(lblMensajeVaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(72, 72, 72))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVaca, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(cmbVacas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeVaca, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addGap(23, 23, 23)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lblMensajeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJornada)
                .addGap(6, 6, 6)
                .addComponent(cmbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblMensajeJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLitrosProducidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/ChatGPT Image 26 may 2026, 14_10_43 (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblImagen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public JComboBox<String> getCmbAño() {
        return cmbAño;
    }

    public JComboBox<String> getCmbDia() {
        return cmbDia;
    }

    public JComboBox<String> getCmbJornada() {
        return cmbJornada;
    }

    public JComboBox<String> getCmbMes() {
        return cmbMes;
    }

    public JComboBox<Vaca> getCmbVacas() {
        return cmbVacas;
    }

    public Integer getLitros() {
        return (Integer) spnLitros.getValue();
    }
    
    public Vaca getVaca() {
        return (Vaca) cmbVacas.getSelectedItem();
    }
    
    public int getAño() {
        return convertirAInt((String) cmbAño.getSelectedItem());
    }
    
    public int getMes() {
        return cmbMes.getSelectedIndex();
    }
    
    private int getDia() {
        return convertirAInt((String) cmbDia.getSelectedItem());
    }
    
    public LocalDate getFecha() {
        int año = getAño();
        int mes = getMes();
        int dia = getDia();
        
        if (año != -1 && mes != 0 && dia != -1) {
            return LocalDate.of(año, mes, dia);
        }
        return null;
    }
    
    public String getJornada() {
        String fecha = (String) cmbJornada.getSelectedItem();
        return (!fecha.equals("Jornada")) ? fecha : null;
    }
    
    private int convertirAInt(String texto) {
        try {
            return Integer.parseInt(texto);
        } catch (NumberFormatException ex) {
            return -1;
        }
    }

    public void setLblMensajeFecha(String mensajeFecha) {
        this.lblMensajeFecha.setText(mensajeFecha);
    }

    public void setLblMensajeJornada(String mensajeJornada) {
        this.lblMensajeJornada.setText(mensajeJornada);
    }

    public void setLblMensajeLitros(String mensajeLitros) {
        this.lblMensajeLitros.setText(mensajeLitros);
    }

    public void setLblMensajeVaca(String mensajeVaca) {
        this.lblMensajeVaca.setText(mensajeVaca);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbJornada;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<Vaca> cmbVacas;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblJornada;
    private javax.swing.JLabel lblLitrosProducidos;
    private javax.swing.JLabel lblMensajeFecha;
    private javax.swing.JLabel lblMensajeJornada;
    private javax.swing.JLabel lblMensajeLitros;
    private javax.swing.JLabel lblMensajeVaca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVaca;
    private javax.swing.JSpinner spnLitros;
    // End of variables declaration//GEN-END:variables
}
