/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Brayan C
 */
public class PanelProduccion extends javax.swing.JPanel {

    /**
     * Creates new form PanelProduccion
     */
    public PanelProduccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        pnlSideBar = new javax.swing.JPanel();
        btnRegistrarProduccion = new javax.swing.JButton();
        lblTituloSideBar = new javax.swing.JLabel();
        pnlLinea = new javax.swing.JPanel();
        btnGestionProduccion = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 0));

        Background.setBackground(new java.awt.Color(255, 255, 255));

        pnlSideBar.setBackground(new java.awt.Color(35, 52, 78));
        pnlSideBar.setForeground(new java.awt.Color(46, 125, 50));
        pnlSideBar.setPreferredSize(new java.awt.Dimension(270, 892));

        btnRegistrarProduccion.setBackground(new java.awt.Color(55, 72, 95));
        btnRegistrarProduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarProduccion.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32 (1).png"))); // NOI18N
        btnRegistrarProduccion.setText("Registrar producción");
        btnRegistrarProduccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnRegistrarProduccion.setBorderPainted(false);
        btnRegistrarProduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarProduccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarProduccion.setIconTextGap(15);

        lblTituloSideBar.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTituloSideBar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloSideBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-registro-32 (1).png"))); // NOI18N
        lblTituloSideBar.setText("Producción");
        lblTituloSideBar.setIconTextGap(10);

        pnlLinea.setBackground(new java.awt.Color(245, 245, 245));
        pnlLinea.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btnGestionProduccion.setBackground(new java.awt.Color(55, 72, 95));
        btnGestionProduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionProduccion.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32_1.png"))); // NOI18N
        btnGestionProduccion.setText("Gestion producción");
        btnGestionProduccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnGestionProduccion.setBorderPainted(false);
        btnGestionProduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionProduccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionProduccion.setIconTextGap(15);

        javax.swing.GroupLayout pnlSideBarLayout = new javax.swing.GroupLayout(pnlSideBar);
        pnlSideBar.setLayout(pnlSideBarLayout);
        pnlSideBarLayout.setHorizontalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        pnlSideBarLayout.setVerticalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTituloSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnRegistrarProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnGestionProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(pnlSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnGestionProduccion() {
        return btnGestionProduccion;
    }

    public JButton getBtnRegistrarProduccion() {
        return btnRegistrarProduccion;
    }

    public JPanel getPanelVacio() {
        return content;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnGestionProduccion;
    private javax.swing.JButton btnRegistrarProduccion;
    private javax.swing.JPanel content;
    private javax.swing.JLabel lblTituloSideBar;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JPanel panelVacio1;
    private javax.swing.JPanel panelVacio2;
    private javax.swing.JPanel panelVacio3;
    private javax.swing.JPanel pnlLinea;
    private javax.swing.JPanel pnlSideBar;
    // End of variables declaration//GEN-END:variables
}
