/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JComboBox;
import javax.swing.JTable;
import modelo.Vaca;

/**
 *
 * @author Brayan C
 */
public class PanelGestionSanidad extends javax.swing.JPanel {

    /**
     * Creates new form PanelGestionSanidad
     */
    public PanelGestionSanidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bacground = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabSanidad = new javax.swing.JTable();
        jblBuscarPorNombre = new javax.swing.JLabel();
        lblSanidad = new javax.swing.JLabel();
        jblInstrucciones = new javax.swing.JLabel();
        cmbVacas = new javax.swing.JComboBox<>();

        bacground.setBackground(new java.awt.Color(255, 255, 255));

        tabSanidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id ", "Tratamiento", "Medicamento", "Dosis", "Fecha", "UUID oculto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabSanidad);

        jblBuscarPorNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jblBuscarPorNombre.setForeground(new java.awt.Color(0, 0, 0));
        jblBuscarPorNombre.setText("Selecciona para ver el historial");
        jblBuscarPorNombre.setIconTextGap(10);

        lblSanidad.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSanidad.setForeground(new java.awt.Color(0, 0, 0));
        lblSanidad.setText("Sanidad");

        jblInstrucciones.setBackground(new java.awt.Color(51, 51, 51));
        jblInstrucciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblInstrucciones.setForeground(new java.awt.Color(102, 102, 102));
        jblInstrucciones.setText("Doble clik sobre un registro para ver informacion completa o editar");

        cmbVacas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbVacas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout bacgroundLayout = new javax.swing.GroupLayout(bacground);
        bacground.setLayout(bacgroundLayout);
        bacgroundLayout.setHorizontalGroup(
            bacgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bacgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblSanidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(447, 447, 447))
            .addGroup(bacgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jblBuscarPorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(562, 562, 562))
            .addGroup(bacgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(393, 393, 393))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(bacgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(cmbVacas, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bacgroundLayout.setVerticalGroup(
            bacgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bacgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblSanidad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblInstrucciones)
                .addGap(19, 19, 19)
                .addComponent(jblBuscarPorNombre)
                .addGap(10, 10, 10)
                .addComponent(cmbVacas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bacground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bacground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTablaSanidad() {
        return tabSanidad;
    }

    public Vaca getVaca() {
        return (Vaca) cmbVacas.getSelectedItem();
    }
    
    

    public JComboBox<Vaca> getJcbAnimal() {
        return cmbVacas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bacground;
    private javax.swing.JComboBox<Vaca> cmbVacas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblBuscarPorNombre;
    private javax.swing.JLabel jblInstrucciones;
    private javax.swing.JLabel lblSanidad;
    private javax.swing.JTable tabSanidad;
    // End of variables declaration//GEN-END:variables
}
