/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Brayan C
 */
public class PanelSanidad extends javax.swing.JPanel {

    /**
     * Creates new form PanelSanidad
     */
    public PanelSanidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        pnlSideBar1 = new javax.swing.JPanel();
        btnRegistrarTratamiento = new javax.swing.JButton();
        lblTituloSideVar = new javax.swing.JLabel();
        pblLinea = new javax.swing.JPanel();
        btnHistorialSanitario = new javax.swing.JButton();
        panelVacio = new javax.swing.JPanel();

        background.setBackground(new java.awt.Color(255, 255, 255));

        pnlSideBar1.setBackground(new java.awt.Color(35, 52, 78));
        pnlSideBar1.setForeground(new java.awt.Color(46, 125, 50));
        pnlSideBar1.setPreferredSize(new java.awt.Dimension(270, 892));

        btnRegistrarTratamiento.setBackground(new java.awt.Color(55, 72, 95));
        btnRegistrarTratamiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32 (1).png"))); // NOI18N
        btnRegistrarTratamiento.setText("Registrar tratamiento");
        btnRegistrarTratamiento.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnRegistrarTratamiento.setBorderPainted(false);
        btnRegistrarTratamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarTratamiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarTratamiento.setIconTextGap(15);

        lblTituloSideVar.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTituloSideVar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloSideVar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSideVar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-vacuna-32.png"))); // NOI18N
        lblTituloSideVar.setText("Sanidad");
        lblTituloSideVar.setIconTextGap(10);

        pblLinea.setBackground(new java.awt.Color(245, 245, 245));
        pblLinea.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout pblLineaLayout = new javax.swing.GroupLayout(pblLinea);
        pblLinea.setLayout(pblLineaLayout);
        pblLineaLayout.setHorizontalGroup(
            pblLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pblLineaLayout.setVerticalGroup(
            pblLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btnHistorialSanitario.setBackground(new java.awt.Color(55, 72, 95));
        btnHistorialSanitario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistorialSanitario.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialSanitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32_1.png"))); // NOI18N
        btnHistorialSanitario.setText("Gestión sanidad");
        btnHistorialSanitario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnHistorialSanitario.setBorderPainted(false);
        btnHistorialSanitario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialSanitario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistorialSanitario.setIconTextGap(15);

        javax.swing.GroupLayout pnlSideBar1Layout = new javax.swing.GroupLayout(pnlSideBar1);
        pnlSideBar1.setLayout(pnlSideBar1Layout);
        pnlSideBar1Layout.setHorizontalGroup(
            pnlSideBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
            .addGroup(pnlSideBar1Layout.createSequentialGroup()
                .addComponent(btnHistorialSanitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addGroup(pnlSideBar1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlSideBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloSideVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pblLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        pnlSideBar1Layout.setVerticalGroup(
            pnlSideBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBar1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTituloSideVar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pblLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnRegistrarTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHistorialSanitario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        panelVacio.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(pnlSideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlSideBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnHistorialSanitario() {
        return btnHistorialSanitario;
    }

    public JButton getBtnRegistrarTratamiento() {
        return btnRegistrarTratamiento;
    }

    public JPanel getPanelVacio() {
        return panelVacio;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnHistorialSanitario;
    private javax.swing.JButton btnRegistrarTratamiento;
    private javax.swing.JLabel lblTituloSideVar;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JPanel pblLinea;
    private javax.swing.JPanel pnlSideBar1;
    // End of variables declaration//GEN-END:variables
}
