/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Brayan C
 */
public class PanelProduccion extends javax.swing.JPanel {

    /**
     * Creates new form PanelProduccion
     */
    public PanelProduccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelSideBar1 = new javax.swing.JPanel();
        btnRegistrarProduccion = new javax.swing.JButton();
        jblProduccion = new javax.swing.JLabel();
        panelLinea = new javax.swing.JPanel();
        btnGestionProduccion = new javax.swing.JButton();
        panelVacio = new javax.swing.JPanel();

        background.setBackground(new java.awt.Color(255, 255, 255));

        panelSideBar1.setBackground(new java.awt.Color(35, 52, 78));
        panelSideBar1.setForeground(new java.awt.Color(46, 125, 50));
        panelSideBar1.setPreferredSize(new java.awt.Dimension(270, 892));
        panelSideBar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarProduccion.setBackground(new java.awt.Color(55, 72, 95));
        btnRegistrarProduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarProduccion.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32 (1).png"))); // NOI18N
        btnRegistrarProduccion.setText("Registrar producción");
        btnRegistrarProduccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnRegistrarProduccion.setBorderPainted(false);
        btnRegistrarProduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarProduccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarProduccion.setIconTextGap(15);
        panelSideBar1.add(btnRegistrarProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 60));

        jblProduccion.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblProduccion.setForeground(new java.awt.Color(255, 255, 255));
        jblProduccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-registro-32 (1).png"))); // NOI18N
        jblProduccion.setText("Producción");
        jblProduccion.setIconTextGap(10);
        panelSideBar1.add(jblProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 48, 200, 54));

        panelLinea.setBackground(new java.awt.Color(245, 245, 245));
        panelLinea.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout panelLineaLayout = new javax.swing.GroupLayout(panelLinea);
        panelLinea.setLayout(panelLineaLayout);
        panelLineaLayout.setHorizontalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelLineaLayout.setVerticalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        panelSideBar1.add(panelLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 120, 200, 3));

        btnGestionProduccion.setBackground(new java.awt.Color(55, 72, 95));
        btnGestionProduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionProduccion.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32_1.png"))); // NOI18N
        btnGestionProduccion.setText("Gestion producción");
        btnGestionProduccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnGestionProduccion.setBorderPainted(false);
        btnGestionProduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionProduccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionProduccion.setIconTextGap(15);
        panelSideBar1.add(btnGestionProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 248, 60));

        panelVacio.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelSideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelSideBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addGap(11, 11, 11))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnGestionProduccion() {
        return btnGestionProduccion;
    }

    public JButton getBtnRegistrarProduccion() {
        return btnRegistrarProduccion;
    }

    public JPanel getPanelVacio() {
        return panelVacio;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnGestionProduccion;
    private javax.swing.JButton btnRegistrarProduccion;
    private javax.swing.JLabel jblProduccion;
    private javax.swing.JPanel panelLinea;
    private javax.swing.JPanel panelSideBar1;
    private javax.swing.JPanel panelVacio;
    // End of variables declaration//GEN-END:variables
}
