/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Brayan C
 */
public class PanelGestionSanidad extends javax.swing.JPanel {

    /**
     * Creates new form PanelGestionSanidad
     */
    public PanelGestionSanidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSanidad = new javax.swing.JTable();
        txtFiltroPorNombre = new javax.swing.JTextField();
        jblBuscarPorNombre = new javax.swing.JLabel();
        jblSanidad = new javax.swing.JLabel();
        jblInstrucciones = new javax.swing.JLabel();
        btnVerInformacion = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaSanidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Animal", "Estado", "Tratamiento", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaSanidad);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 190, 848, 532));

        txtFiltroPorNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtFiltroPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, 282, -1));

        jblBuscarPorNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblBuscarPorNombre.setForeground(new java.awt.Color(0, 0, 0));
        jblBuscarPorNombre.setText("Buscar por nombre");
        jblBuscarPorNombre.setIconTextGap(10);
        jPanel1.add(jblBuscarPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, 282, -1));

        jblSanidad.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblSanidad.setForeground(new java.awt.Color(0, 0, 0));
        jblSanidad.setText("Sanidad");
        jPanel1.add(jblSanidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 401, 49));

        jblInstrucciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jblInstrucciones.setForeground(new java.awt.Color(0, 0, 0));
        jblInstrucciones.setText("Da clik sobre un animal para ver informacion completa fo editar");
        jPanel1.add(jblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 455, -1));

        btnVerInformacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerInformacion.setText("Ver información");
        btnVerInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVerInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 170, 50));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 170, 50));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVerInformacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblBuscarPorNombre;
    private javax.swing.JLabel jblInstrucciones;
    private javax.swing.JLabel jblSanidad;
    private javax.swing.JTable tablaSanidad;
    private javax.swing.JTextField txtFiltroPorNombre;
    // End of variables declaration//GEN-END:variables
}
