/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Brayan C
 */
public class PanelGanado extends javax.swing.JPanel {

    /**
     * Creates new form panelGanado
     */
    public PanelGanado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelSideBar1 = new javax.swing.JPanel();
        btnRegistrarGanado = new javax.swing.JButton();
        lblTituloSideBar = new javax.swing.JLabel();
        pnlLinea = new javax.swing.JPanel();
        btnListaGanado = new javax.swing.JButton();
        panelVacio = new javax.swing.JPanel();

        background.setBackground(new java.awt.Color(255, 255, 255));

        panelSideBar1.setBackground(new java.awt.Color(35, 52, 78));
        panelSideBar1.setForeground(new java.awt.Color(46, 125, 50));
        panelSideBar1.setPreferredSize(new java.awt.Dimension(270, 892));

        btnRegistrarGanado.setBackground(new java.awt.Color(55, 72, 95));
        btnRegistrarGanado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarGanado.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarGanado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32 (1).png"))); // NOI18N
        btnRegistrarGanado.setText("Registrar ganado");
        btnRegistrarGanado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnRegistrarGanado.setBorderPainted(false);
        btnRegistrarGanado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarGanado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarGanado.setIconTextGap(15);

        lblTituloSideBar.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTituloSideBar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloSideBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-vaca-70.png"))); // NOI18N
        lblTituloSideBar.setText("Ganado");
        lblTituloSideBar.setIconTextGap(10);

        pnlLinea.setBackground(new java.awt.Color(245, 245, 245));
        pnlLinea.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btnListaGanado.setBackground(new java.awt.Color(55, 72, 95));
        btnListaGanado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListaGanado.setForeground(new java.awt.Color(255, 255, 255));
        btnListaGanado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder/icons8-ganado-32_1.png"))); // NOI18N
        btnListaGanado.setText("Gestionar ganado");
        btnListaGanado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 14, 1, 1, new java.awt.Color(0, 0, 0)));
        btnListaGanado.setBorderPainted(false);
        btnListaGanado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaGanado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListaGanado.setIconTextGap(15);

        javax.swing.GroupLayout panelSideBar1Layout = new javax.swing.GroupLayout(panelSideBar1);
        panelSideBar1.setLayout(panelSideBar1Layout);
        panelSideBar1Layout.setHorizontalGroup(
            panelSideBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarGanado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSideBar1Layout.createSequentialGroup()
                .addComponent(btnListaGanado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(panelSideBar1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelSideBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        panelSideBar1Layout.setVerticalGroup(
            panelSideBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideBar1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTituloSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnRegistrarGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnListaGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        panelVacio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelSideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(panelVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelSideBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelVacio() {
        return panelVacio;
    }
    
    public JButton getBtnRegistrarGanado() {
        return btnRegistrarGanado;
    }

    public JButton getBtnListaGanado() {
        return btnListaGanado;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnListaGanado;
    private javax.swing.JButton btnRegistrarGanado;
    private javax.swing.JLabel lblTituloSideBar;
    private javax.swing.JPanel panelSideBar1;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JPanel pnlLinea;
    // End of variables declaration//GEN-END:variables
}
