/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import modelo.Vaca;

/**
 *
 * @author Brayan C
 */
public class PanelRegistrarTratamiento extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrarTratamiento
     */
    public PanelRegistrarTratamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistrarGanado = new javax.swing.JPanel();
        jblTitle = new javax.swing.JLabel();
        jblFechaTratamiento = new javax.swing.JLabel();
        jblTipoDeTratamiento = new javax.swing.JLabel();
        jblMensajeNombre = new javax.swing.JLabel();
        jblMensajeFecha = new javax.swing.JLabel();
        jblMensajeRazas = new javax.swing.JLabel();
        jblMensajeEstadoProduccion = new javax.swing.JLabel();
        jcbAnimalAAplicar = new javax.swing.JComboBox<>();
        jcbMes = new javax.swing.JComboBox<>();
        jcbDia = new javax.swing.JComboBox<>();
        jcbAño = new javax.swing.JComboBox<>();
        jcbTipoTratamiento = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jblAnimalAAplicar = new javax.swing.JLabel();
        jblDosis = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        jblObservaciones = new javax.swing.JLabel();
        jblMedicamento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jblMensajeNombre1 = new javax.swing.JLabel();

        panelRegistrarGanado.setBackground(new java.awt.Color(245, 245, 245));

        jblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblTitle.setForeground(new java.awt.Color(0, 0, 0));
        jblTitle.setText("Registro veterinario");

        jblFechaTratamiento.setBackground(new java.awt.Color(0, 0, 0));
        jblFechaTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblFechaTratamiento.setForeground(new java.awt.Color(0, 0, 0));
        jblFechaTratamiento.setText("Fecha del tratamiento");

        jblTipoDeTratamiento.setBackground(new java.awt.Color(0, 0, 0));
        jblTipoDeTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblTipoDeTratamiento.setForeground(new java.awt.Color(0, 0, 0));
        jblTipoDeTratamiento.setText("Tipo de tratamiento");

        jblMensajeNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeNombre.setForeground(new java.awt.Color(204, 0, 51));
        jblMensajeNombre.setText("\n");

        jblMensajeFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeFecha.setForeground(new java.awt.Color(204, 0, 51));

        jblMensajeRazas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeRazas.setForeground(new java.awt.Color(204, 0, 51));

        jblMensajeEstadoProduccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeEstadoProduccion.setForeground(new java.awt.Color(204, 0, 51));

        jcbAnimalAAplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbAnimalAAplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jcbMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes" }));
        jcbMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jcbDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día" }));
        jcbDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jcbAño.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        jcbAño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAñoActionPerformed(evt);
            }
        });

        jcbTipoTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbTipoTratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VACUNACION", "DESPARASITACION", "DESGARRAPATIZACION", "VITAMINIZACION", "ANTIBIOTICO", "TRATAMIENTO RESPIRATORIO", "TRATAMIENTO DIGESTIVO", "CURACION HERIDAS", "CONTROL FIEBRE", "CONTROL MASTITIS", "SUPLEMENTACION MINERAL", "CONTROL PARASITOS", "INSEMINACION", "CONTROL REPRODUCTIVO", "REVISION VETERINARIA", "CIRUGIA" }));
        jcbTipoTratamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbTipoTratamiento.setMaximumSize(new java.awt.Dimension(138, 50));
        jcbTipoTratamiento.setMinimumSize(new java.awt.Dimension(137, 49));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jblAnimalAAplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblAnimalAAplicar.setForeground(new java.awt.Color(0, 0, 0));
        jblAnimalAAplicar.setText("Animal a aplicar");

        jblDosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblDosis.setForeground(new java.awt.Color(0, 0, 0));
        jblDosis.setText("Dosis");

        txtMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtDosis.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jblObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblObservaciones.setForeground(new java.awt.Color(0, 0, 0));
        jblObservaciones.setText("Observaciones");

        jblMedicamento.setBackground(new java.awt.Color(0, 0, 0));
        jblMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblMedicamento.setForeground(new java.awt.Color(0, 0, 0));
        jblMedicamento.setText("Medicamento");

        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jblId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblId.setForeground(new java.awt.Color(0, 0, 0));
        jblId.setText("Id del tratamiento");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jblMensajeNombre1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblMensajeNombre1.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout panelRegistrarGanadoLayout = new javax.swing.GroupLayout(panelRegistrarGanado);
        panelRegistrarGanado.setLayout(panelRegistrarGanadoLayout);
        panelRegistrarGanadoLayout.setHorizontalGroup(
            panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblId, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243)
                        .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jblMensajeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                            .addComponent(jcbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jblMensajeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jblTipoDeTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jblMensajeRazas, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jblMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jblMensajeEstadoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jblAnimalAAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                            .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbAnimalAAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jblMensajeNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jblFechaTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(72, 72, 72)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jcbTipoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 123, Short.MAX_VALUE))
        );
        panelRegistrarGanadoLayout.setVerticalGroup(
            panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblId, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jblMensajeNombre)
                .addGap(9, 9, 9)
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblAnimalAAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblObservaciones))
                .addGap(6, 6, 6)
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarGanadoLayout.createSequentialGroup()
                        .addComponent(jcbAnimalAAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblMensajeNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblFechaTratamiento))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelRegistrarGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jblMensajeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblTipoDeTratamiento)
                .addGap(6, 6, 6)
                .addComponent(jcbTipoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jblMensajeRazas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblMedicamento)
                .addGap(10, 10, 10)
                .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jblMensajeEstadoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistrarGanado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistrarGanado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAñoActionPerformed

    public Vaca getAnimalAAplicar() {
        return (Vaca) jcbAnimalAAplicar.getSelectedItem();
    }

    public JComboBox<String> getJcbAño() {
        return jcbAño;
    }

    public JComboBox<String> getJcbDia() {
        return jcbDia;
    }

    public JComboBox<String> getJcbMes() {
        return jcbMes;
    }

    public String getTipoTratamiento() {
        return jcbTipoTratamiento.getSelectedItem().toString();
    }

    public String getDosis() {
        return txtDosis.getText();
    }

    public String getMedicamento() {
        return txtMedicamento.getText();
    }

    public String getObservaciones() {
        return txtObservaciones.getText();
    }

    public JComboBox<Vaca> getJcbAnimalAAplicar() {
        return jcbAnimalAAplicar;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public String getId() {
        return txtId.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblAnimalAAplicar;
    private javax.swing.JLabel jblDosis;
    private javax.swing.JLabel jblFechaTratamiento;
    private javax.swing.JLabel jblId;
    private javax.swing.JLabel jblMedicamento;
    private javax.swing.JLabel jblMensajeEstadoProduccion;
    private javax.swing.JLabel jblMensajeFecha;
    private javax.swing.JLabel jblMensajeNombre;
    private javax.swing.JLabel jblMensajeNombre1;
    private javax.swing.JLabel jblMensajeRazas;
    private javax.swing.JLabel jblObservaciones;
    private javax.swing.JLabel jblTipoDeTratamiento;
    private javax.swing.JLabel jblTitle;
    private javax.swing.JComboBox<Vaca> jcbAnimalAAplicar;
    private javax.swing.JComboBox<String> jcbAño;
    private javax.swing.JComboBox<String> jcbDia;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JComboBox<String> jcbTipoTratamiento;
    private javax.swing.JPanel panelRegistrarGanado;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
