/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Brayan C
 */
public class PanelCrearCuenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelCrearCuenta
     */
    public PanelCrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelIniciarSesion = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombresYApellidos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCorreoElectronico = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombres = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtNombreUsuario = new javax.swing.JTextField();
        lblNombreUsuario = new javax.swing.JLabel();
        lblNombreFinca = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtNombreFinca = new javax.swing.JTextField();
        pswContraseña = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtVereda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mensajeNombres = new javax.swing.JLabel();
        mensajeUsuario = new javax.swing.JLabel();
        mensajeContraseña = new javax.swing.JLabel();
        mensajeCorreo = new javax.swing.JLabel();
        mensajeNombreDeLaFinca = new javax.swing.JLabel();
        mensajeUbicacion = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox<>();
        cmbMunicipio = new javax.swing.JComboBox<>();

        background.setBackground(new java.awt.Color(255, 255, 255));

        panelIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        panelIniciarSesion.setForeground(new java.awt.Color(245, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Crear una cuenta");

        lblNombresYApellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombresYApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lblNombresYApellidos.setText("Nombres y apellidos");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreoElectronico.setText("Corrreo electrónico");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombres.setText("Nombres y apellidos");
        txtNombres.setBorder(null);
        txtNombres.setCaretColor(new java.awt.Color(0, 0, 0));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreUsuario.setText("Nombre de usuario");
        txtNombreUsuario.setBorder(null);
        txtNombreUsuario.setCaretColor(new java.awt.Color(0, 0, 0));

        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsuario.setText("Nombre de usuario");

        lblNombreFinca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreFinca.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreFinca.setText("Nombre de la finca");

        lblUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        lblUbicacion.setText("Ubicación");

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseña.setText("Contraseña");

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCorreo.setText("Correo electrónico");
        txtCorreo.setBorder(null);
        txtCorreo.setCaretColor(new java.awt.Color(0, 0, 0));

        txtNombreFinca.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreFinca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreFinca.setText("Nombre de la finca");
        txtNombreFinca.setBorder(null);
        txtNombreFinca.setCaretColor(new java.awt.Color(0, 0, 0));

        pswContraseña.setBackground(new java.awt.Color(255, 255, 255));
        pswContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pswContraseña.setText("**************");
        pswContraseña.setBorder(null);
        pswContraseña.setCaretColor(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        txtVereda.setBackground(new java.awt.Color(255, 255, 255));
        txtVereda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVereda.setForeground(new java.awt.Color(153, 153, 153));
        txtVereda.setText("Vereda");
        txtVereda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vereda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txtVereda.setCaretColor(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));

        mensajeNombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeNombres.setForeground(new java.awt.Color(204, 0, 0));

        mensajeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeUsuario.setForeground(new java.awt.Color(204, 0, 0));

        mensajeContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeContraseña.setForeground(new java.awt.Color(204, 0, 0));

        mensajeCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeCorreo.setForeground(new java.awt.Color(204, 0, 0));

        mensajeNombreDeLaFinca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeNombreDeLaFinca.setForeground(new java.awt.Color(204, 0, 0));

        mensajeUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeUbicacion.setForeground(new java.awt.Color(204, 0, 0));

        cmbDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento" }));
        cmbDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbMunicipio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipio" }));
        cmbMunicipio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblNombresYApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblNombreFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtNombreFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                        .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensajeNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(mensajeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(mensajeCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(mensajeNombreDeLaFinca, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(mensajeUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(mensajeContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                        .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                                .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVereda, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(566, 566, 566))
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblNombresYApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(mensajeNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(mensajeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mensajeCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblNombreFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(txtNombreFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addGap(26, 26, 26)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(mensajeNombreDeLaFinca, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(lblUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVereda, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarSesionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addComponent(mensajeUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(mensajeContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                    .addComponent(panelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPasswordField getPwsContraseña() {
        return pswContraseña;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public JTextField getTxtNombreFinca() {
        return txtNombreFinca;
    }

    public JTextField getTxtNombres() {
        return txtNombres;
    }

    public JTextField getTxtUsuario() {
        return txtNombreUsuario;
    }

    public JTextField getTxtVereda() {
        return txtVereda;
    }
    
    public JComboBox<String> getJcbDepartamento() {
        return cmbDepartamento;
    }

    public JComboBox<String> getJcbMunicipio() {
        return cmbMunicipio;
    }
    
    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public String getCorreo() {
        String correo = txtCorreo.getText();
        return (verificarCamposDeTexto(correo, "Correo electrónico")) ? correo.trim() : null;
    }

    public String getNombreFinca() {
        String nombreDeLaFinca = txtNombreFinca.getText();
        return (verificarCamposDeTexto(nombreDeLaFinca, "Nombre de la finca")) ? nombreDeLaFinca.trim() : null;
    }

    public String getNombres() {
        String nombres = txtNombres.getText();
        return (verificarCamposDeTexto(nombres, "Nombres y apellidos")) ? nombres.trim() : null;
    }

    public String getUsuario() {
        String usuario = txtNombreUsuario.getText();
        return (verificarCamposDeTexto(usuario, "Nombre de usuario")) ? usuario.trim() : null;
    }

    public String getContraseña() {
        String contraseña = String.valueOf(pswContraseña.getPassword());
        return (verificarCamposDeTexto(contraseña, "**************")) ? contraseña.trim() : null;
    }

    public String getVereda() {
        String vereda = txtVereda.getText();
        return (verificarCamposDeTexto(vereda, "Vereda")) ? vereda.trim() : null;
    }

    public void setJcbDepartamento(JComboBox<String> jcbDepartamento) {
        this.cmbDepartamento = jcbDepartamento;
    }

    public void setJcbMunicipio(JComboBox<String> jcbMunicipio) {
        this.cmbMunicipio = jcbMunicipio;
    }

    public void setJpfContraseña(String texto) {
        this.pswContraseña.setText(texto);
    }

    public void setTxtCorreo(String texto) {
        this.txtCorreo.setText(texto);
    }

    public void setTxtNombreFinca(String texto) {
        this.txtNombreFinca.setText(texto);
    }

    public void setTxtNombres(String texto) {
        this.txtNombres.setText(texto);
    }

    public void setTxtUsuario(String texto) {
        this.txtNombreUsuario.setText(texto);
    }

    public void setTxtVereda(String texto) {
        this.txtVereda.setText(texto);
    }

    public void setMensajeContraseña(String mensajeContraseña) {
        this.mensajeContraseña.setText(mensajeContraseña);
    }

    public void setMensajeCorreo(String mensajeCorreo) {
        this.mensajeCorreo.setText(mensajeCorreo);
    }

    public void setMensajeNombreDeLaFinca(String mensajeNombreDeLaFinca) {
        this.mensajeNombreDeLaFinca.setText(mensajeNombreDeLaFinca);
    }

    public void setMensajeNombres(String mensajeNombres) {
        this.mensajeNombres.setText(mensajeNombres);
    }

    public void setMensajeUbicacion(String mensajeUbicacion) {
        this.mensajeUbicacion.setText(mensajeUbicacion);
    }

    public void setMensajeUsuario(String mensajeUsuario) {
        this.mensajeUsuario.setText(mensajeUsuario);
    }
    
    private boolean verificarCamposDeTexto(String campoDeTexto, String campoAValidar) {
        return campoDeTexto != null && !campoDeTexto.trim().isEmpty() && !campoDeTexto.trim().equals(campoAValidar);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JComboBox<String> cmbMunicipio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblNombreFinca;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNombresYApellidos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel mensajeContraseña;
    private javax.swing.JLabel mensajeCorreo;
    private javax.swing.JLabel mensajeNombreDeLaFinca;
    private javax.swing.JLabel mensajeNombres;
    private javax.swing.JLabel mensajeUbicacion;
    private javax.swing.JLabel mensajeUsuario;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreFinca;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtVereda;
    // End of variables declaration//GEN-END:variables
}
