/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.time.LocalDate;
import javax.swing.JButton;
import javax.swing.JComboBox;
import modelo.Vaca;

/**
 *
 * @author Brayan C
 */
public class PanelRegistrarTratamiento extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrarTratamiento
     */
    public PanelRegistrarTratamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTipoTratamiento = new javax.swing.JLabel();
        lblMensajeIdTratamiento = new javax.swing.JLabel();
        lblMensajeFecha = new javax.swing.JLabel();
        lblMensajeTratamientos = new javax.swing.JLabel();
        lblMensajeMedicamento = new javax.swing.JLabel();
        cmbVacas = new javax.swing.JComboBox<>();
        cmbMes = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        cmbAño = new javax.swing.JComboBox<>();
        cmbTratamientos = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        lblAnimalAplicar = new javax.swing.JLabel();
        lblDosis = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        lblObservaciones = new javax.swing.JLabel();
        lblMedicamento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObservaciones = new javax.swing.JTextArea();
        lblIdTratamiento = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        lblMensajeDosis = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(245, 245, 245));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Registro veterinario");

        lblFecha.setBackground(new java.awt.Color(0, 0, 0));
        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha");

        lblTipoTratamiento.setBackground(new java.awt.Color(0, 0, 0));
        lblTipoTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipoTratamiento.setForeground(new java.awt.Color(0, 0, 0));
        lblTipoTratamiento.setText("Tratamiento");

        lblMensajeIdTratamiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensajeIdTratamiento.setForeground(new java.awt.Color(204, 0, 51));
        lblMensajeIdTratamiento.setText("\n");

        lblMensajeFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensajeFecha.setForeground(new java.awt.Color(204, 0, 51));

        lblMensajeTratamientos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensajeTratamientos.setForeground(new java.awt.Color(204, 0, 51));

        lblMensajeMedicamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensajeMedicamento.setForeground(new java.awt.Color(204, 0, 51));

        cmbVacas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbVacas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes" }));
        cmbMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día" }));
        cmbDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbAño.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        cmbAño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAñoActionPerformed(evt);
            }
        });

        cmbTratamientos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTratamientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tratamiento", "Vacunación", "Desparasitación", "Desgarrapatización", "Vitaminización", "Antibiótico", "Tratamiento respiratorio", "Tratamiento digestivo", "Curación de heridas", "Control de fiebre", "Control de mastitis", "Suplementación mineral", "Control de parásitos", "Inseminación", "Control reproductivo", "Revisión veterinaria", "Cirugía" }));
        cmbTratamientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbTratamientos.setMaximumSize(new java.awt.Dimension(138, 50));
        cmbTratamientos.setMinimumSize(new java.awt.Dimension(137, 49));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAnimalAplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAnimalAplicar.setForeground(new java.awt.Color(0, 0, 0));
        lblAnimalAplicar.setText("Animal a aplicar");

        lblDosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDosis.setForeground(new java.awt.Color(0, 0, 0));
        lblDosis.setText("Dosis");

        txtMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtDosis.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lblObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblObservaciones.setForeground(new java.awt.Color(0, 0, 0));
        lblObservaciones.setText("Observaciones");

        lblMedicamento.setBackground(new java.awt.Color(0, 0, 0));
        lblMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMedicamento.setForeground(new java.awt.Color(0, 0, 0));
        lblMedicamento.setText("Medicamento");

        txtAreaObservaciones.setColumns(20);
        txtAreaObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAreaObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtAreaObservaciones);

        lblIdTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdTratamiento.setForeground(new java.awt.Color(0, 0, 0));
        lblIdTratamiento.setText("Id del tratamiento");

        txtIdentificador.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lblMensajeDosis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensajeDosis.setForeground(new java.awt.Color(204, 0, 51));
        lblMensajeDosis.setText("\n");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblIdTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMensajeTratamientos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTipoTratamiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                        .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbDia, 0, 96, Short.MAX_VALUE))
                                    .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMensajeIdTratamiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMensajeFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbVacas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdentificador, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(lblAnimalAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(174, 174, 174)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(backgroundLayout.createSequentialGroup()
                                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                                        .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(lblMensajeDosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(backgroundLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(lblMensajeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimalAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cmbVacas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMensajeDosis)))
                .addComponent(lblIdTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblMensajeIdTratamiento)
                        .addGap(4, 4, 4)
                        .addComponent(lblFecha)
                        .addGap(5, 5, 5)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(lblMensajeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoTratamiento)
                .addGap(5, 5, 5)
                .addComponent(cmbTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblMensajeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAñoActionPerformed

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public JComboBox<String> getCmbAño() {
        return cmbAño;
    }

    public JComboBox<String> getCmbDia() {
        return cmbDia;
    }

    public JComboBox<String> getCmbMes() {
        return cmbMes;
    }

    public JComboBox<String> getCmbTratamientos() {
        return cmbTratamientos;
    }

    public JComboBox<Vaca> getCmbVacas() {
        return cmbVacas;
    }

    public Vaca getVaca() {
        return (Vaca) cmbVacas.getSelectedItem();
    }
    
    public String getIdentificador() {
        String identificador = txtIdentificador.getText();
        return (validarCampos(identificador)) ? identificador : null;
    }
    
    public int getAño() {
        return convertirAInt((String) cmbAño.getSelectedItem());
    }
    
    public int getMes() {
        return cmbMes.getSelectedIndex();
    }
    
    private int getDia() {
        return convertirAInt((String) cmbDia.getSelectedItem());
    }
    
    public LocalDate getFecha() {
        int año = getAño();
        int mes = getMes();
        int dia = getDia();
        
        if (año != -1 && mes != 0 && dia != -1) {
            return LocalDate.of(año, mes, dia);
        }
        return null;
    }
    
    public String getTratamiento() {
        String tratamiento = (String) cmbTratamientos.getSelectedItem();
        return (!tratamiento.equals("Tratamiento")) ? tratamiento : null;
    }
    
    private boolean validarCampos(String texto) {
        return (texto != null && !texto.trim().isEmpty());
    }
    
    public String getMedicamento() {
        String medicamento = txtMedicamento.getText();
        return (validarCampos(medicamento)) ? medicamento : null;
    }
    
    public String getDosis() {
        String dosis = txtDosis.getText();
        return (validarCampos(dosis)) ? dosis : null;
    }
    
    public String getObservaciones() {
        String observaciones = txtAreaObservaciones.getText();
        return (validarCampos(observaciones)) ? observaciones : "Sin observaciones";
    }

    public void setLblMensajeDosis(String mensajeDosis) {
        this.lblMensajeDosis.setText(mensajeDosis);
    }

    public void setLblMensajeFecha(String mensajeFecha) {
        this.lblMensajeFecha.setText(mensajeFecha);
    }

    public void setLblMensajeIdTratamiento(String mensajeIdTratamiento) {
        this.lblMensajeIdTratamiento.setText(mensajeIdTratamiento);
    }

    public void setLblMensajeMedicamento(String mensajeMedicamento) {
        this.lblMensajeMedicamento.setText(mensajeMedicamento);
    }

    public void setLblMensajeTratamientos(String mensajeTratamientos) {
        this.lblMensajeTratamientos.setText(mensajeTratamientos);
    }
     private int convertirAInt(String texto) {
        try {
            return Integer.parseInt(texto);
        } catch (NumberFormatException ex) {
            return -1;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<String> cmbTratamientos;
    private javax.swing.JComboBox<Vaca> cmbVacas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnimalAplicar;
    private javax.swing.JLabel lblDosis;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIdTratamiento;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblMensajeDosis;
    private javax.swing.JLabel lblMensajeFecha;
    private javax.swing.JLabel lblMensajeIdTratamiento;
    private javax.swing.JLabel lblMensajeMedicamento;
    private javax.swing.JLabel lblMensajeTratamientos;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblTipoTratamiento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAreaObservaciones;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtMedicamento;
    // End of variables declaration//GEN-END:variables
}
